version: '3'

services:
  python-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - APP_DEBUG=True
      - APP_FRONTEND_URL=http://localhost:3000
    restart: unless-stopped 